### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by Martins3** [kernelrookie/lite-vm#1]
- [ ] setup kvm template :  https://github.com/TheLartians/ModernCppStarter
- [ ] do survey on unikernel, libos, firecracker, qemu and kvmtool
- [ ] locate core modules
- [ ] write code
